// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalPokedex.Models;

namespace MinimalPokedex.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181203211756_Type3")]
    partial class Type3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinimalPokedex.Models.Ability", b =>
                {
                    b.Property<int>("AbilityID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbilityName");

                    b.HasKey("AbilityID");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("MinimalPokedex.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonID");

                    b.Property<int>("Attack");

                    b.Property<int>("Defense");

                    b.Property<int>("EggSteps");

                    b.Property<int>("ExperienceGrowth");

                    b.Property<int>("Generation");

                    b.Property<int>("HP");

                    b.Property<bool>("IsLegendary");

                    b.Property<string>("Name");

                    b.Property<int>("SpAttack");

                    b.Property<int>("SpDefense");

                    b.Property<int>("Speed");

                    b.Property<int?>("Type1TypeID");

                    b.Property<int?>("Type2TypeID");

                    b.HasKey("PokemonID");

                    b.HasIndex("Type1TypeID");

                    b.HasIndex("Type2TypeID");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("MinimalPokedex.Models.PokemonAbilities", b =>
                {
                    b.Property<int>("PokemonID");

                    b.Property<int>("AbilityID");

                    b.HasKey("PokemonID", "AbilityID");

                    b.HasIndex("AbilityID");

                    b.ToTable("PokemonAbilities");
                });

            modelBuilder.Entity("MinimalPokedex.Models.Type", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName");

                    b.HasKey("TypeID");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("MinimalPokedex.Models.Pokemon", b =>
                {
                    b.HasOne("MinimalPokedex.Models.Type", "Type1")
                        .WithMany()
                        .HasForeignKey("Type1TypeID");

                    b.HasOne("MinimalPokedex.Models.Type", "Type2")
                        .WithMany()
                        .HasForeignKey("Type2TypeID");
                });

            modelBuilder.Entity("MinimalPokedex.Models.PokemonAbilities", b =>
                {
                    b.HasOne("MinimalPokedex.Models.Ability", "Ability")
                        .WithMany("PokemonAbilities")
                        .HasForeignKey("AbilityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MinimalPokedex.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonAbilities")
                        .HasForeignKey("PokemonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
