// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalPokedex.Models;

namespace MinimalPokedex.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181201160738_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinimalPokedex.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonID");

                    b.Property<int>("Generation");

                    b.Property<string>("Name");

                    b.Property<string>("Type1");

                    b.Property<string>("Type2");

                    b.HasKey("PokemonID");

                    b.ToTable("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
